### ISSUE TITLE
How to prevent submit in nested form

### ISSUE THREAD

**Issue by joelNguyenn1010** [react-hook-form/react-hook-form#1005]
I have a nested form that looks like this
```
//this is the form
<form>

// this for quick add functionality and display the data from the form above
<form>
</form>

</form>
```

The problem I have is when the children submit the data, it also trigger the submit from the parent, is there any way to prevent this from happening.
P/S: also, how to trigger submit form <button>, something like <button onClick={() => handleSubmit()}>submit</button>

Thanks

**Comment by bluebill1049** [comment]
1. you shouldn't nested your form
2. if you only update to update not submit, set your button to type="button"
3. trigger submit form `handleSubmit()()` it's a curry function

let me know if those helps :)

**Comment by brayanL** [comment]
@bluebill1049 maybe you can provide an example more specific please, I have the same problem. I don't know if I have to remove the form tag too..!

**Comment by bluebill1049** [comment]
@brayanL can you produce a simple codesandbox for me to take a look?

**Comment by brayanL** [comment]
I fixed the problem I had to remove onSubmit of form tag and add it on onClick button :)

**Comment by bluebill1049** [comment]
awesome! @brayanL

**Comment by vikas26294** [comment]
I also ran into same issue. I was able to solve it by modifying my submit function to

```
  const onSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    // this part is for stopping parent forms to trigger their submit
    if (event) {
      // sometimes not true, e.g. React Native	      // sometimes not true, e.g. React Native
      if (typeof event.preventDefault === 'function') {
        event.preventDefault();
      }
      if (typeof event.stopPropagation === 'function') {
        // prevent any outer forms from receiving the event too
        event.stopPropagation();
      }
    }

    return formHandlers.handleSubmit(async (values) => {
       // your code can go here
    })(event);
  };
```

**Comment by gaozhidf** [comment]
```
<Form>
  <Form onSubmit={e => {
    e.preventDefault();
    // your code
    e.stopPropagation();
  }} >
  </Form>
</Form>
```

**Comment by McGern** [comment]
@vikas26294 Your solution is perfect for what I need - Thanks. We are using MUI with forms in dialogs, and while the forms themselves are not nested, the react synthetic event propagation still happens, so this solution works well.

Because we are using this in a lot of places, I would like to create a reusable function but am having trouble with the currying and typescript, so wondering if I could chance my arm and ask for some more help please?

We are generally using the pattern

<form onSubmit={handleSubmit(specificFormSubmitHandler)}>

and would like to update with something like this, so there isn't much rework

<form onSubmit={nestedFormSubmit(handleSubmit(specificFormSubmitHandler))}>

I tried doing something simple to curry the function, but am getting stuck with the typescript and return values. Any help would be much appreciated.

**Comment by wilsonfaustino** [comment]
> I also ran into same issue. I was able to solve it by modifying my submit function to
> 
> ```
>   const onSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
>     // this part is for stopping parent forms to trigger their submit
>     if (event) {
>       // sometimes not true, e.g. React Native
>       if (typeof event.preventDefault === 'function') {
>         event.preventDefault();
>       }
>       if (typeof event.stopPropagation === 'function') {
>         // prevent any outer forms from receiving the event too
>         event.stopPropagation();
>       }
>     }
> 
>     return formHandlers.handleSubmit(async (values) => {
>        // your code can go here
>     })(event);
>   };
> ```

Thank you very much. This helped me a lot. :heart:

**Comment by mikewudev** [comment]
> Because we are using this in a lot of places, I would like to create a reusable function but am having trouble with the currying and typescript, so wondering if I could chance my arm and ask for some more help please?

Here's what I've done for TS

```js
export function stopPropagate(callback: (...args: any[]) => void) {
  return (e: {stopPropagation: () => void}) => {
    e.stopPropagation()
    callback()
  }
}
```

And now it's just another wrapper function

```js
<form onSubmit={stopPropagate(handleSubmit(submit))}>
```

**Comment by titenis** [comment]
Or if using `useForm` and `<FormProvider />`:
```
const methods = useForm();

return (
 <FormProvider {...methods}>
          <form
            onSubmit={e => {
              e.stopPropagation();

              return methods.handleSubmit(onSubmit)(e);
            }}
          >
```

**Comment by ryancolorcafe** [comment]
Fyi you can use the `BaseSyntheticEvent` as the type and call `stopPropagation` like this:

```
const onSubmit = (data: FormData, e: BaseSyntheticEvent) => {
  e.stopPropagation();
};

const useFormMethods = useForm<FormData>({});
const { handleSubmit } = useFormMethods;

return (
  <FormProvider {...useFormMethods}>
    <form
      onSubmit={e => {
        handleSubmit(onSubmit)(e)
      }}
    >
      {/* ... */}
    </form>
  </FormProvider>
);
```

**Comment by ngimdock** [comment]
I have the same problem in my case, i have nested form but i use react hook form and can't acess to the `event` variable and stop the propagation. Some one can help me plz
