### ISSUE TITLE
watch returns old value for one render cycle when used with react-beautiful-dnd and useFieldArray

### ISSUE THREAD

**Issue by williamtetlow** [react-hook-form/react-hook-form#3981]
**Describe the bug**
When using `watch` to display a value in an element that can be drag and dropped with `react-beautiful-dnd` the watched value is one render cycle behind after moving.

**To Reproduce**

1. Go to sandbox
2. Click on second element in list
3. Drag to top of list
4. See that the `Watched: Bill x` value flickers with previous value

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-move-not-working-pmxqs?file=/src/index.js

**Expected behavior**
The watched value should be in sync with the `fields` value from `useFieldArray`

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 87

**Comment by bluebill1049** [comment]
I don't think it's a good idea to `useWatch` at the root?

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/105421875-e6aed780-5c96-11eb-8c10-4cfaa4d3fc17.mov

without `useWatch`, also the layout shifted a bit, looks like its due to padding?

**Comment by williamtetlow** [comment]
Sorry I was trying replicate the setup in our system but it is actually a few components down in the hierarchy so let me update the example to match

**Comment by williamtetlow** [comment]
@bluebill1049 thanks for getting back to me. I've updated the example slightly to better reflect how it is structured in our app.

https://codesandbox.io/s/react-hook-form-usefieldarray-move-not-working-pmxqs?file=/src/index.js

The issue we are having is we have a header element that allows you to expand and hide each field item from the array. 

That element uses the value from watch to display the text so when they are typing a new name into the input it also displays it in the header.

The flickering isn't caused by layout but the data from watch (this also happens with the `watch` function as well as the hook). It's a bit more obvious in our app but you can see it in this video that when I move the items the top row flickers and shows `Watched: Bill 1` again before displaying `Watched: Bill 2`. 

https://user-images.githubusercontent.com/9057181/105465941-7e0e2d80-5c8b-11eb-88e5-18759a25f804.mov

**Comment by williamtetlow** [comment]
This screenshot of the data returned from watching the field array might demonstrate the problem better.

You can see after moving the elements the watched value returns the old data one more time before returning the correct data.

![Screenshot 2021-01-22 at 08 38 56](https://user-images.githubusercontent.com/9057181/105467224-4acc9e00-5c8d-11eb-8cd5-86680b017017.png)

**Comment by bluebill1049** [comment]
I think this is one of the weaknesses in terms of design for v6 with `useFieldArray`, the good news is we are improving the data structure and perf in v7. 

can you try to supply `fields` object as the default value or the `watch`? or provide a defaultValue for useWatch for the actual field array? see if this fix the issue with "data" delay.

**Comment by williamtetlow** [comment]
@bluebill1049 I saw your comments of v6 vs v7 in other issues and thought it may be related 😄  

I tried setting the `fields` as the default value but it didn't seem to work. I have a workaround currently where I store the order from the drag-n-drop in a ref and use that order if it doesn't match the one returned by watch so I can use that for now.

FYI from debugging it looked like at this point in the code `fieldArrayValuesRef.current` would have the correct value but it would `fieldValues` one more time instead.

https://github.com/react-hook-form/react-hook-form/blob/0a0f2bf959aff7065dee18137d6fc9f26a082644/src/useForm.ts#L825-L830

**Comment by bluebill1049** [comment]
> FYI from debugging it looked like at this point in the code `fieldArrayValuesRef.current` would have the correct value but it would use `fieldValues` one more time instead.

Thanks for the debugging! v7 should solve this problem, this piece of logic is removed in v7.

**Comment by williamtetlow** [comment]
No probs, looking forward to v7!

Thanks for your help and great library, I'll close this issue 👌

**Comment by bluebill1049** [comment]
Thanks for your understanding @williamtetlow I think next week, we should be able to cut an alpha version of v7. I will make sure to test this issue out with it as well.

Let me know if you have any feedback or concerns with v7 as well:  https://github.com/react-hook-form/react-hook-form/discussions/3714

**Comment by Brodzko** [comment]
For those looking for this, the issue still remains with `useWatch` but in my case using `watch` directly instead solved it :)
