### ISSUE TITLE
Nested useFieldArray - nested children do not show default values after appended in parent

### ISSUE THREAD

**Issue by wayne-unolab** [react-hook-form/react-hook-form#993]
**Describe the bug**
Form data structure in this Codesandbox:

> test[]
> -- name
> -- nested[]
> ----name

When using useFieldArray in a nested way, newly appended 1st level data (in this case is "test") does not have default value for its child array "nested" even called append like below.
`append({ name: "append", nested: [{ name: "append nested by parent" }] })`

**To Reproduce**
1. Go to below sandbox link
2. Click on 'Append'
3. See newly appended one without a default children in "nested" 😭

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-n0xph?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
Expected to see newly appended one with default value in "nested" like the 1st one by defaultValues in useForm.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 80.0.3987.87 (Official Build) (64-bit)

**Additional context**
I guess it should be expected behaviour for nested useFieldArray? Hope I didnt misuse useFieldArray as i cannot found any example demonstrating nested usage.
Or is there any workaround for case like this?

**Comment by bluebill1049** [comment]
thanks for the issue, however, I don't think it is valid.
```
defaultValues: {
      test: [{ name: "useFieldArray", nested: [{ name: "nested" }] }]
    }
``` 

you only have default value for the first item right?

**Comment by jd-erreape** [comment]
The initial config will be

![Screenshot 2020-02-08 at 02 12 19](https://user-images.githubusercontent.com/1223781/74076472-850b4400-4a18-11ea-9c7f-ab69dda893fd.png)

Then  after clicking on the Move button at the bottom of the page we will get this config

![Screenshot 2020-02-08 at 02 11 17](https://user-images.githubusercontent.com/1223781/74076496-9f452200-4a18-11ea-9b8c-8ae86de1c63d.png)

Now this is the result of having clicked 'Submit' with the initial config and then just after clicking Move button

![Screenshot 2020-02-08 at 02 11 30](https://user-images.githubusercontent.com/1223781/74076521-b71ca600-4a18-11ea-94b8-504eaff912cc.png)

Let me know if it's still not clear!!! thanks for replying so fast.

**Comment by bluebill1049** [comment]
I see after the move, some of the nested data get lost. I think that's a valid issue and it's not the same as the current one. would you like to raise a separate issue?

**Comment by jd-erreape** [comment]
Done https://github.com/react-hook-form/react-hook-form/issues/994 👍

**Comment by wayne-unolab** [comment]
> thanks for the issue, however, I don't think it is valid.
> 
> ```
> defaultValues: {
>   test: [{ name: "useFieldArray", nested: [{ name: "nested" }] }]
> }
> ```
> 
> you only have default value for the first item right?

Yes it works well when defining defaultValues in useForm.

**However** what i want to bring out is that when performing "Append" in the 1st level data[please look at the obj i wrote inside "append()" ] 
`
<button
          type="button"
          onClick={() => {
            append({
              name: "append",
              nested: [{ name: "append nested by parent" }]
            });
          }}
        >
          append
        </button>
`
What im trying to do is to append a child here in 1st level with a predefined item in its "nested".
Is there a way to achieve this?

**To Reproduce**
1. Go to Codesandbox link https://codesandbox.io/s/react-hook-form-usefieldarray-n0xph?fontsize=14&hidenavigation=1&theme=dark
2. Click on "Append"
3. The orange one is the one just appended. And there is no value in its "nested".
![image](https://user-images.githubusercontent.com/57429171/74079756-aac73600-4a76-11ea-8887-18f520123413.png)


** Expected **
I expect the appended child should have value in "nested" with "name" -> "append nested by parent" as i implemented the "Append" action in the above. I illustrated my expected outcome in the screenshot below.
<img width="1465" alt="Screenshot 2020-02-08 at 1 37 37 PM" src="https://user-images.githubusercontent.com/57429171/74079912-a439be00-4a78-11ea-9eda-2ab1a4886413.png">

@bluebill1049 Thanks for your prompt reply on this. And i sry that if i described my situation badly ...
Please help to check again my problem here again. If it is really "not a bug" then i may need to find a workaround for my project.

**Comment by bluebill1049** [comment]
hey @wayne-unolab thanks for the detailed reply and issue report again :) and you are very understanding and polite too. appreciated that ❤️ 

i am working on the docs, can you take a look this example: https://codesandbox.io/s/react-hook-form-usefieldarray-h24uq see if it's been resolved your problem. i will take another look at your issue tonight.

**Comment by wayne-unolab** [comment]
@bluebill1049 Sad to say that my problem still there in ur codesandbox example :(

Mine is different from the one mentioned by jd. And i hope i did explain it is a better way in my reply above. 😂
Let me know if u need anymore clarification this issue when u look into in later. Cheers.

**Comment by bluebill1049** [comment]
oh, I see the problem now. that's not possible. it's controlled by a separate custom hook.

**Comment by wayne-unolab** [comment]
oh ... then i guess i need to figure out a workaround for this. Or do u hv any suggestion on this?
And I bet this is not a rare scenario when creating complex form. 🤔

**Comment by bluebill1049** [comment]
I would try to use single custom useFieldArray for this.

**Comment by wayne-unolab** [comment]
How to use a single useFieldArray for this case if the "nested" items need to be append/remove/etc ?

**Comment by bluebill1049** [comment]
> How to use a single useFieldArray for this case if the "nested" items need to be append/remove/etc?

you are right, that's not the right approach instead probably try to invoke child `useFieldArray`'s append and other actions.

**Comment by bluebill1049** [comment]
closing this issue, feel free to follow up with questions.

**Comment by meman** [comment]
Hi,

I thought i might chime into this issue rather than open a new one. So what is the answers to this, to simple not have nested arrays?

One thing I have noticed which is a little odd is the behaviour of prepending or inserting into the first position of the first useFieldArray array. The nested array seems to get the default value, is this intended behaviour?

https://codesandbox.io/s/react-hook-form-usefieldarray-n0xph?fontsize=14&hidenavigation=1&theme=dark

**using append**
<img width="708" alt="Screenshot 2020-07-23 at 17 24 47" src="https://user-images.githubusercontent.com/6372537/88311994-851ea800-cd09-11ea-99d0-0f03f5446d55.png">

**using prepend**
<img width="717" alt="Screenshot 2020-07-23 at 17 24 57" src="https://user-images.githubusercontent.com/6372537/88311986-82bc4e00-cd09-11ea-9414-586d37c24971.png">

**Comment by bluebill1049** [comment]
@meman if you set up defatulfVlaues, it will get populated, the simplest way is not having default nested value if you don't want this behavior. (if I understand correctly)

**Comment by meman** [comment]
Hi @bluebill1049 , thanks for the reply. I do want the default values. What i am a little lost with is why prepend or inserting at position 0 has the default value while appending or inserting anywhere else does not.

**Comment by bluebill1049** [comment]
> Hi @bluebill1049 , thanks for the reply. I do want the default values. What i am a little lost with is why prepend or inserting at position 0 has the default value while appending or inserting anywhere else does not.

I think that's because, at position 0, you have `defaultValues` for it right?

**Comment by meman** [comment]
Aaaaa right ok, that would make sense. So doing something like this...
```
const methods = useForm({
  defaultValues: {
    filters: {and: [{or: [defaultRule]}]}
  },
   mode: 'onChange'
});
```

only adds the default for the first element. So if i wanted to a default the rest, is there a way to do it via some like the above?

**Comment by bluebill1049** [comment]
if you want default for the rest, you will have to supply that into append/prepend api.

**Comment by meman** [comment]
But that does not work, if i do 

```
append({or: [defaultRule]})
```
nested array is empty when i use useFieldArray. For now i have a hack which is to detect the empty array and append one from the nested arrays context. It works however i was hoping there would be a better way to do it

**Comment by bluebill1049** [comment]
at the nestFieldArray:

`useEffect(() => { append({ defaultRules }) }, [])`

useFieldArray only take cares per FieldArray.

**Comment by meman** [comment]
Ok cool thanks
